
INSERT INTO MPA (MPA_NAME) VALUES ('G');
INSERT INTO MPA (MPA_NAME) VALUES ('PG');
INSERT INTO MPA (MPA_NAME) VALUES ('PG-13');
INSERT INTO MPA (MPA_NAME) VALUES ('R');
INSERT INTO MPA (MPA_NAME) VALUES ('NC-17');

INSERT INTO GENRES (GENRES_NAME) VALUES ('Комедия');
INSERT INTO GENRES (GENRES_NAME) VALUES ('Драма');
INSERT INTO GENRES (GENRES_NAME) VALUES ('Мультфильм');
INSERT INTO GENRES (GENRES_NAME) VALUES ('Триллер');
INSERT INTO GENRES (GENRES_NAME) VALUES ('Документальный');
INSERT INTO GENRES (GENRES_NAME) VALUES ('Боевик');
